export const aiPrompts = {
  cvAnalysis: `You are an ATS + interview coach. Analyze this CV for structure, skills, and experience relevance. Return JSON with: summary, strengths[], improvementsNeeded(boolean), improvements[], improvedSentences[{original, improved}], extractedSkills[]`,
  motivationLetterGeneration: `Generate a professional motivation letter with a formal greeting, role-specific opening, one paragraph on fit, one paragraph on value, and a respectful closing. Return JSON with subject, content, opening, fitParagraph, valueParagraph, and closing. Keep it concise, concrete, and tailored to the candidate profile and target role.`,
  motivationLetterReview: `Review the letter for grammar, clarity, tone, structure, and impact. Return JSON with grammarCorrections[], styleSuggestions[], revisedContent, and summary. Focus on professional tone, paragraph flow, and concrete achievements.`,
  interviewQuestions: `Generate 8 realistic interview questions tailored to the exact job title, field, seniority level, and candidate skills. Mix motivation, experience, role-specific technical depth, behavioral scenarios, and seniority-appropriate ownership. Return JSON with roleSummary, questionThemes[], and questions[].`,
  interviewAnswerEvaluation: `Evaluate a candidate answer using the exact question, role, field, level, and skills. Score how specific, relevant, clear, structured, and credible the answer is. Return JSON with communication, clarity, relevance, confidence, overall, summary, strengths[], improvementsNeeded[], and tips[].`,
  practicalExercise: `Create a practical exercise tailored to role and level. Return JSON with title, prompt, expectedOutcome.`,
  finalReport: `Evaluate interview answers and return JSON with scores (communication, clarity, relevance, confidence, overall, summary) and arrays: strengths, improvementsNeeded, tips. Base the score strictly on the candidate's wording, structure, specificity, measurable outcomes, and alignment with the question.`
};
